-- 코드를 작성해주세요
SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH IS NOT NULL AND fi.LENGTH > 10
AND fi.ID IN (
    SELECT ID
    FROM (
        SELECT ID, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) as rnk
        FROM FISH_INFO
        WHERE LENGTH > 10
    ) tmp
    WHERE rnk = 1
)
ORDER BY fi.ID ASC;
